### ISSUE TITLE
Problems with /login.html

### ISSUE THREAD

**Issue by ralphtheninja** [ptahproject/ptahcrowd#12]
I'm using the latest master of examples/ptah_models and latest master of ptah_crowd. I added links to ptah_models so I can test /login.html etc and got this error when accessing /login.html

When I go to the login.html page I get this error from ptah

2012-01-11 02:20:23,677 WARNI [ptah][MainThread] Can't find layout 'ptah-page' for context '<pyramid.traversal.DefaultRootFactory instance at 0xa019dec>'

**Comment by fafhrd91** [comment]
its not really a bug. ptah_crowd uses 'ptah-page' layout and you should redefine it in your project.
you should use ptah_minicms with ptah_crowd.

**Comment by ralphtheninja** [comment]
Ok then, perhaps it should say so in the readme for ptah_crowd. Thanks for
your replies!

2012/1/11 Nikolay Kim <
reply@reply.github.com
