### ISSUE TITLE
missing CSRF in ptahcrowd login

### ISSUE THREAD

**Issue by runyaga** [ptahproject/ptahcrowd#21]
```
  <input type="hidden" name="${view.csrfname}" value="${view.token}" />
```

is missing

**Comment by fafhrd91** [comment]
what is the reason to use csrf protection for login form?

**Comment by runyaga** [comment]
now that I think about it it's not useful.

I used login form to do form tutorial and it was kinda late

Alan Runyan
Enfold Systems
